# -*- coding: utf-8 -*-
"""[모험가 길드].ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11Hm3-86QP_Kd7mrELKEU_9KOUYnD6p-P
"""

import sys
r=sys.stdin.readline
N=int(r())
l=list(map(int,r().split()))
l.sort()

res=0
cnt=0
for i in l:
	cnt+=1
	if i==cnt:
		res+=1
		cnt=0

print(res)